ARG WEBUI_DOCKER_TAG
FROM ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
COPY backend/mfg_start.sh /app/backend/mfg_start.sh
RUN apt update && apt install -y procps
RUN pip3 install uv debugpy
CMD [ "bash", "mfg_start.sh"]